apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dataloader-go
  description: |
    A generics based implementation of the Facebook's dataloader pattern
  annotations:
    github.com/project-slug: einride/dataloader-go
    github.com/team-slug: einride/team-cloud-control
    backstage.io/source-location: url:https://github.com/einride/dataloader-go/tree/master/
spec:
  type: library
  lifecycle: production
  owner: team-cloud-control
